# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
class loadingScreen(QtWidgets.QMainWindow):
   

    def __init__(self) -> None:
        """Inherited from QtWidgets.QMainWindow"""
        super().__init__()
        self.setupUi()
        self.show()
        
    def setupUi(self):

        self.setFixedSize(447, 395)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.CircularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.CircularProgressBarBase.setGeometry(
            QtCore.QRect(10, 10, 320, 320))
        self.CircularProgressBarBase.setStyleSheet(
            "QFrame{border-radius:150px;}")
        self.CircularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBarBase.setObjectName("CircularProgressBarBase")
        self.CircularBg = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.CircularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.CircularBg.setStyleSheet("QFrame{\n"
                                      "border-radius:150px;\n"
                                      "background-color:qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255));}")
        self.CircularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularBg.setObjectName("CircularBg")
        self.CircularProgress = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.CircularProgress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.CircularProgress.setStyleSheet("QFrame{\n"
                                            "border-radius: 150px;\n"
                                            "background-color:rgba(77, 77, 127,0) }")
        self.CircularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgress.setObjectName("CircularProgress")
        self.Container = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.Container.setGeometry(QtCore.QRect(25, 25, 270, 270))
        self.Container.setStyleSheet("QFrame{\n"
                                     "border-radius:135px;\n"
                                     "background-color: rgb(77,77,127);\n"
                                     "}")
        self.Container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Container.setObjectName("Container")
        self.labelJarvis = QtWidgets.QLabel(self.Container)
        self.labelJarvis.setGeometry(QtCore.QRect(50, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.labelJarvis.setFont(font)
        self.labelJarvis.setStyleSheet(
            "QLabel{background-color:none;color:white;}")
        self.labelJarvis.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJarvis.setObjectName("labelJarvis")
        self.percentlabel = QtWidgets.QLabel(self.Container)
        self.percentlabel.setGeometry(QtCore.QRect(70, 40, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(90)
        self.percentlabel.setFont(font)
        self.percentlabel.setStyleSheet(
            "QLabel{background-color:none;color:white}")
        self.percentlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.percentlabel.setObjectName("percentlabel")
        self.labelInitialising = QtWidgets.QLabel(self.Container)
        self.labelInitialising.setGeometry(QtCore.QRect(50, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.labelInitialising.setFont(font)
        self.labelInitialising.setStyleSheet("QLabel{\n"
                                             "color:white;\n"
                                             "border-radius:15%;\n"
                                             "background-color: rgb(93,93,154)};")
        self.labelInitialising.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInitialising.setObjectName("labelInitialising")
        self.labelCredits = QtWidgets.QLabel(self.Container)
        self.labelCredits.setGeometry(QtCore.QRect(70, 220, 121, 31))
        self.labelCredits.setStyleSheet("QLabel{color:white}")
        self.labelCredits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCredits.setObjectName("labelCredits")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def changeProgress(self, value) -> bool:
        """Value in percent"""

        stylesheet = """
        QFrame{\nborder-radius:150px;\nbackground-color:qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:{STOP_1} rgba(255, 0, 127, 0), stop:{STOP_2} rgba(85, 170, 255, 255));}"""

        if value == 100:
            stop1 = "1.0"
            stop2 = "1.0"
            
            return True
        else:
            progress = (100 - value)/100.0
            stop1 = str(progress - 0.001)
            stop2 = str(progress)

        newstylesheet = stylesheet.replace(
            "{STOP_1}", stop1).replace("{STOP_2}", stop2)

        self.CircularBg.setStyleSheet(newstylesheet)
        self.percentlabel.setText(f"{value}<sup>%</sup>")
        return False
 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelJarvis.setText(_translate("MainWindow", "Jarvis"))
        self.percentlabel.setText(_translate("MainWindow", "0<sup>%</sup>"))
        self.labelInitialising.setText(
            _translate("MainWindow", "Initialising..."))
        self.labelCredits.setText(_translate("MainWindow", "By Tanmay Daga"))
        
