# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setFixedSize(610, 398)
        self.setupUi()
    def setupUi(self):
        
        
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 610, 398))
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.settingsOcon = QtWidgets.QPushButton(self.page)
        self.settingsOcon.setGeometry(QtCore.QRect(550, 20, 51, 51))
        self.settingsOcon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsOcon.setStyleSheet("QPushButton{border-radius:35px;background-color:rgba(255,255,255,0);}")
        self.settingsOcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsOcon.setIcon(icon)
        self.settingsOcon.setIconSize(QtCore.QSize(32, 32))
        self.settingsOcon.setFlat(False)
        self.settingsOcon.setObjectName("settingsOcon")
        self.inputBox = QtWidgets.QTextEdit(self.page)
        self.inputBox.setGeometry(QtCore.QRect(20, 340, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputBox.setFont(font)
        self.inputBox.setStyleSheet("QTextEdit{border-radius:25px;background-color:rgba(255,255,255,50);}")
        self.inputBox.setObjectName("inputBox")
        self.micButton = QtWidgets.QPushButton(self.page)
        self.micButton.setGeometry(QtCore.QRect(550, 340, 61, 51))
        self.micButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.micButton.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0)}")
        self.micButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/microphoneoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.micButton.setIcon(icon1)
        self.micButton.setIconSize(QtCore.QSize(32, 32))
        self.micButton.setObjectName("micButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 511, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 507, 307))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.suggestionsButton = QtWidgets.QPushButton(self.page)
        self.suggestionsButton.setGeometry(QtCore.QRect(550, 90, 51, 51))
        self.suggestionsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suggestionsButton.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);}")
        self.suggestionsButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/suggestion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suggestionsButton.setIcon(icon2)
        self.suggestionsButton.setIconSize(QtCore.QSize(32, 32))
        self.suggestionsButton.setObjectName("suggestionsButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-20, 0, 631, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget.addWidget(self.page_2)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Jarvis"))
        self.stackedWidget.setStyleSheet(_translate("MainWindow", "QTextEdit{border-radius:25px;background-color:rgba(255,255,255,50);}"))
        self.suggestionsButton.setStatusTip(_translate("MainWindow", "Suggestions"))

